### ISSUE TITLE
Failed to add to slack

### ISSUE THREAD

**Issue by xuezhma** [JackCuthbert/kaomoji-slack-app#15]
Tried to add to slack on https://kaomoji.d1.jckcthbrt.io/,
Got this error after authorizing team:

```

{
"name": "error",
"length": 323,
"severity": "ERROR",
"code": "23502",
"detail": "Failing row contains (5, T3V85R6B0, xoxp-131277856374-129919232625-192247937269-a8ff1846c0f82b405d92..., null, null, 2017-06-02 22:36:05.364, 2017-06-02 22:36:05.364).",
"schema": "public",
"table": "teams",
"column": "bot_user_id",
"file": "execMain.c",
"line": "1732",
"routine": "ExecConstraints"
}


```

**Comment by JackCuthbert** [comment]
Sorry about that! Probably a permissions scope issue with bot users, will take a look shortly.

Also probably shouldn't be exposing tokens in the error response, I'll be removing this one from the DB.

**Comment by JackCuthbert** [comment]
Oops, it was a schema issue on the prod db, it's been a while since I've worked on this. I've fixed this up and deployed a new version of the app anyway. Give it another go 😸

**Comment by xuezhma** [comment]
Awesome. Thx
